receivers:
  otlpjsonfile/traces:
    include:
      - "/var/log/otel_input/*traces*.json"
  otlpjsonfile/metrics:
    include:
      - "/var/log/otel_input/*metrics*.json"
  otlpjsonfile/logs:
    include:
      - "/var/log/otel_input/*logs*.json"

processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 2G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s


exporters:
  # Data sources: traces, metrics, logs
  otlp/grpc:
    endpoint: 192.168.1.56:4317
  otlphttp:
    endpoint: http://192.168.1.56:4318


service:
  pipelines:
    traces:
      receivers: [otlpjsonfile/traces]
      processors: [memory_limiter, batch]
      exporters: [otlp/grpc, otlphttp]
    metrics:
      receivers: [otlpjsonfile/metrics]
      processors: [memory_limiter, batch]
      exporters: [otlp/grpc, otlphttp]
    logs:
      receivers: [otlpjsonfile/logs]
      processors: [memory_limiter, batch]
      exporters: [otlp/grpc, otlphttp]
  telemetry:
    logs:
      level: DEBUG


